---
Title: Testing whether I can recover ATE from model with random intercepts
---

## Setup

```{r}
library(furrr)
library(tidyverse)
library(data.table)
library(arrow)
library(rmsb)
```

## Load model

```{r}
model <- readRDS("./2-hosp/models/model_hosp_rcs_cluster_no_int.rds")
```

## Marginalized State Occupancy Probabilities for model 1 (full int, non clustered)
```{r}
baseline_df <- filter(df, week == 1) |> as.data.table()
```

```{r}
write_SOP <- function(i, tx, baseline_df){
  
  row <- baseline_df[i]
  
  sops <-
  soprobMarkovOrdm(
    model,
    data = list(tx = tx, ecog_fstcnt = row$ecog_fstcnt, diagnosis = row$diagnosis, age = row$age, gender = row$gender, albumin = row$albumin, c_reactive_protein = row$c_reactive_protein, yprev=row$yprev),
    times = 1:26,
    ylevels = 1:5,
    absorb = 5,
    tvarname = "week",
    pvarname = "yprev"
  )
  
  # Because of the size of the data, only use the first 500 MCMC draws
  sops <- sops[1:500,,]
  
  sops <- as.data.table(sops)

  # Rename columns
  setnames(sops,
           old = c("V1", "V2", "V3", "value"),
           new = c("draw", "week", "state", "sop"))
  
  sops$week <- as.integer(sops$week)
  sops$state <- as.factor(sops$state)
  sops$tx <- tx
  sops$i <- i
  
  folder <- glue::glue("./2-hosp/output/sops-sim-model/marginalized_sop_{tx}/msop_{i}.parquet")
  
  arrow::write_parquet(
    x = sops,
    sink = folder
    )
}
```

### Generate marginalized SOPs

```{r}
future::plan(future.callr::callr, workers=10)

# Control
if (generate_SOPS) {
    furrr::future_walk(1:nrow(baseline_df), \(x) write_SOP(x, 0, baseline_df),
                       .progress=TRUE,
                       .options = furrr_options(seed=TRUE))
}
```

```{r}
# Treatment
if (generate_SOPS) {
    furrr::future_walk(1:nrow(baseline_df), \(x) write_SOP(x, 1, baseline_df),
                       .progress=TRUE,
                       .options = furrr_options(seed=TRUE))
}
```

### Read maginalized SOPs

```{r}
# Get list of all files
files <- fs::dir_ls("./2-hosp/output/sops-sim-model/marginalized_sop_0/", glob = "*.parquet")

# Read in each parquet file as a data.frame and merge into a data.table
soc_df <- map(files, \(x) arrow::read_parquet(x), .progress=TRUE) |> rbindlist()

# Average SOPs over covariate settings -- for each state, day, and MCMC draw
soc_df <- soc_df[, .(sop = mean(sop)), by = .(state, week, draw, tx)]
soc_df[, state := as.factor(state)]
```

```{r}
# Get list of all files
files <- fs::dir_ls("./2-hosp/output/sops-sim-model/marginalized_sop_1/", glob = "*.parquet")

# Read in each parquet file as a data.frame and merge into a data.table
tx_df <- map(files, \(x) arrow::read_parquet(x), .progress=TRUE) |> rbindlist()

# Average SOPs over covariate settings -- for each state, day, and MCMC draw
tx_df <- tx_df[, .(sop = mean(sop)), by = .(state, week, draw, tx)]
tx_df[, state := as.factor(state)]
```

```{r}
sop_df <-
  bind_rows(soc_df, tx_df) |>
  mutate(tx = as.factor(tx))
```

### Plotting

#### Marginalized SOPs

```{r}
fig_marginalized <-
sop_df |>
  ggplot() +
  aes(x = week, y = sop) +
  ggdist::stat_lineribbon(aes(fill = state, linetype = tx),
                          linewidth = 0.6,
                          alpha = 0.5,
                          .width = c(0.95)) +
  scale_color_viridis_d(end = 0.9) +
  scale_fill_viridis_d(end = 0.9) +
  scale_x_continuous(breaks = seq(1, 26, by=4)) +
  scale_y_continuous(breaks = seq(0, 1, by=0.1)) +
  coord_cartesian(ylim = c(0, 1)) +
  labs(x = "Study Week",
   y = "SOP",
   subtitle = "Marginalized state occupancy probabilities",
   fill = "State",
   linetype = "Treatment")

fig_marginalized

ggsave("./img/hosp-marginalized_sop-full-int.svg", fig_marginalized, width = 10, height = 6)
```

Stacked bar chart using median point estimate

```{r}
sop_df |>
  group_by(state, week, tx) |> 
  summarise(sop = median(sop)) |> 
  ggplot() +
  aes(x = week, y = sop, fill = state) +
  geom_col(position = "fill") +
  scale_fill_viridis_d(end = 0.9) +
  scale_x_continuous(breaks = 1:26) +
  scale_y_continuous(breaks = seq(0, 1, by=0.25)) +
  coord_cartesian(ylim = c(0, 1)) +
  facet_wrap(~tx, nrow=1) +
  labs(x = "Study Week",
   y = "SOP",
   subtitle = "Marginalized state occupancy probabilities",
   fill = "State",
   linetype = "Treatment")

ggsave("./img/hosp-marginalized_sop-stacked-full-int.svg", width = 10, height = 6)
```

Posterior of Estimand (Time out of hospital)

```{r}
difference_in_mean_time_home <- sop_df |> 
  filter(state == 1) |> 
  group_by(draw, tx) |> 
  summarise(mean_weeks = sum(sop)) |> 
  pivot_wider(id_cols = draw, names_from = tx, names_prefix = "mean_time_tx_", values_from = mean_weeks) |> 
  summarise(difference = mean_time_tx_1 - mean_time_tx_0)

difference_in_mean_time_home |> 
  ggplot() +
  aes(x = difference) +
  ggdist::stat_dist_halfeye(fill = "orange")

ggsave("./img/hosp-difference-in-mean-time-home-full-int.svg", width = 8, height = 7)
```


