---
Title : QoL Data Preparation
---

## Setup

```{r}
library(tidyverse)
library(data.table)
library(arrow)
```

```{r}
df <- read_parquet("./data/hosp_long_complete.parquet")
```

## Code Y 
```{r}
df <- df |> 
    select(-na_est) |>
    mutate(
      y = case_when(
        death == 1      ~ 5,
        unplanned_stay ~ 4,
        er_visit       ~ 3,
        in_hospital    ~ 2,
        TRUE           ~ 1
      )
    ) |> 
    relocate(pat_id, tx, y)
```

## Add lag + reduce to weeks for simulations

We will reduce the granularity of time to weeks for the simulations.

```{r}
# Convert time-scale to weeks
# Day zero is counted as week 0 (baseline), Day 1 counts towards week 1.
df_weeks <- df |> 
    mutate(
        week = ceiling(day / 7),
        surv_weeks = ceiling(survival_time/7)
    ) |> 
    group_by(pat_id, week) |> 
    arrange(desc(y)) |> 
    slice_head(n = 1) |> 
    arrange(pat_id, week) |> 
    group_by(pat_id) |> 
    mutate(
        yprev = case_when(
            TRUE ~ lag(y, n = 1, order_by = week)
        ),
        yprev = factor(yprev, levels = 1:4, ordered = FALSE), #death = 5 doesn't exist in yprev
        gap = 1) |> 
    slice(-1) |> 
    ungroup() |> 
    relocate(pat_id, tx, y, yprev)
```

## Create data set with ypprev (2 weeks ago) for second order model

```{r}
df_ypprev <- df_weeks  |> 
    group_by(pat_id) |> 
    mutate(
        ypprev = case_when(
            TRUE ~ lag(yprev, n = 1, order_by = week)
        ),
        ypprev = factor(ypprev, levels = 1:4, ordered = FALSE)) |> 
    slice(-1) |> 
    ungroup() |> 
    relocate(pat_id, tx, y, yprev, ypprev)
```

## Data daily

```{r}
df_daily <- df |> 
    group_by(pat_id, day) |> 
    arrange(desc(y)) |> 
    slice_head(n = 1) |> 
    arrange(pat_id, day) |> 
    group_by(pat_id) |> 
    mutate(
        yprev = case_when(
            TRUE ~ lag(y, n = 1, order_by = day)
        ),
        yprev = factor(yprev, levels = 1:4, ordered = FALSE),
        ypprev = case_when(
            TRUE ~ lag(yprev, n = 1, order_by = day)
        ),
        ypprev = factor(ypprev, levels = 1:4, ordered = FALSE),
        gap = 1) |> 
    slice(-1) |> 
    ungroup() |> 
    relocate(pat_id, tx, y, yprev, ypprev)
```

## Export

```{r}
write_parquet(df_weeks, sink = "./data/hosp_long_weeks.parquet")
write_parquet(df_ypprev, sink = "./data/hosp_long_weeks_two_lags.parquet")
write_parquet(df_daily, sink = "./data/hosp_long_daily.parquet")
```