---
Title: Examining Type I Error with Resampling - No Interaction time x yrev FREQUENTIST
---

## Setup
```{r}
# Load Libraries
library(Hmisc)
library(ggplot2)
library(arrow)
library(tidyverse)
library(data.table)
library(furrr)
library(glue)
library(fs)
library(here)
library(rms)
library(VGAM)
```

## Load data

```{r}
set.seed(1234)

# Load full dataset
# If we reasign the treatment again and again, emergency room visits are a bit too rare and mess up transitions
# We therefore collapse staet 3 and 4
df <- read_parquet(here("data", "hosp_long_weeks_anon.parquet")) |> 
    mutate(
        y = if_else(y == 4, 3, y),
        y = if_else(y == 5, 4, y),
        yprev = if_else(yprev == "4", "3", yprev),
        yprev = factor(yprev)) |> 
    select(id, tx, y, yprev, time = week)

df_ypprev <- read_parquet(here("data", "hosp_long_weeks_two_lags.parquet")) |> 
    mutate(
        y = if_else(y == 4, 3, y),
        y = if_else(y == 5, 4, y),
        yprev = if_else(yprev == "4", "3", yprev),
        yprev = factor(yprev)) |> 
    select(id = pat_id, tx, y, yprev, ypprev, time = week)
```

## Simulation function

```{r}
run_simulation_iteration <- function(iter_num, base_path, full_data) {
    # This function runs one full simulation iteration.
    
    # --- 1. Setup for the current iteration ---
    set.seed(123 + iter_num)

    tx_ids <- full_data |> 
        distinct(id) |> 
        sample_frac(2/3) |> pull(id)

    data_for_model <- full_data |> 
        mutate(
            tx = if_else(id %in% tx_ids, "1", "0"),
            tx = factor(tx, levels = c(0, 1)))
    
    rm(full_data)
    
    if (nrow(data_for_model) > 0) {
        model <- tryCatch({ 
            vglm(
                ordered(y)  ~ tx + rcs(time, 4) + yprev,
                cumulative(reverse = TRUE, parallel = FALSE ~  rcs(time, 4)),
                data = data_for_model)
            
        }, error = function(e) {
            message(glue("ERROR in iteration {iter_num}: {e$message}"))
            
            saveRDS(data_for_model, file.path(iter_path, "problematic_data.rds"))
            
            return(NULL)
        })
        
        # --- 7. Save the results ONLY if the model ran successfully ---
        if (!is.null(model)) {
            summary_df <- summary(model)@coef3 |> data.frame() |> 
                rownames_to_column("term")

            return(summary_df)
        }
    }
    return(NULL)
}
```

## Simulation function w/ linear interaction

```{r}
run_simulation_iteration_int <- function(iter_num, base_path, full_data) {
    # This function runs one full simulation iteration.
    
    # --- 1. Setup for the current iteration ---
    set.seed(123 + iter_num)

    tx_ids <- full_data |> 
        distinct(id) |> 
        sample_frac(2/3) |> pull(id)

    data_for_model <- full_data |> 
        mutate(
            tx = if_else(id %in% tx_ids, "1", "0"),
            tx = factor(tx, levels = c(0, 1)))
    
    rm(full_data)
    
    if (nrow(data_for_model) > 0) {
        model <- tryCatch({ 
            vglm(
                ordered(y)  ~ tx + rcs(time, 4) + yprev + time %ia% yprev,
                cumulative(reverse = TRUE, parallel = FALSE ~  rcs(time, 4)),
                data = data_for_model)
            
        }, error = function(e) {
            message(glue("ERROR in iteration {iter_num}: {e$message}"))
            
            saveRDS(data_for_model, file.path(iter_path, "problematic_data.rds"))
            
            return(NULL)
        })
        
        # --- 7. Save the results ONLY if the model ran successfully ---
        if (!is.null(model)) {
            summary_df <- summary(model)@coef3 |> data.frame() |> 
                rownames_to_column("term")

            return(summary_df)
        }
    }
    return(NULL)
}
```

## Simulation function 2-order Markov

```{r}
run_simulation_iteration_second <- function(iter_num, base_path, full_data) {
    # This function runs one full simulation iteration.
    
    # --- 1. Setup for the current iteration ---
    set.seed(123 + iter_num)

    tx_ids <- full_data |> 
        distinct(id) |> 
        sample_frac(2/3) |> pull(id)

    data_for_model <- full_data |> 
        mutate(
            tx = if_else(id %in% tx_ids, "1", "0"),
            tx = factor(tx, levels = c(0, 1)))
    
    rm(full_data)
    
    if (nrow(data_for_model) > 0) {
        model <- tryCatch({ 
            vglm(
                ordered(y)  ~ tx + rcs(time, 4) + yprev + ypprev,
                cumulative(reverse = TRUE, parallel = FALSE ~  rcs(time, 4)),
                data = data_for_model)
            
        }, error = function(e) {
            message(glue("ERROR in iteration {iter_num}: {e$message}"))
            
            saveRDS(data_for_model, file.path(iter_path, "problematic_data.rds"))
            
            return(NULL)
        })
        
        # --- 7. Save the results ONLY if the model ran successfully ---
        if (!is.null(model)) {
            summary_df <- summary(model)@coef3 |> data.frame() |> 
                rownames_to_column("term")

            return(summary_df)
        }
    }
    return(NULL)
}
```

## Run Parallelized Simulation
```{r}
N_SIMULATIONS <- 1000
OUTPUT_PATH <- here("2-hosp", "output", "sim-resampling-H0-no-int-freq")
RESULTS_FILE <- "sim-resampling-H0-no-int-freq.parquet"
N_CORES <- 8

t1 <- Sys.time()

message(glue("Starting {N_SIMULATIONS} new simulations on {N_CORES} cores..."))

future::plan(future.callr::callr, workers = N_CORES)

# --- Run Simulations in Parallel ---
results <- furrr::future_map_dfr(
    .x = 1:N_SIMULATIONS,
    .f = ~ run_simulation_iteration(
        iter_num = .x,
        full_data = df
    ),
    .options = furrr_options(seed = TRUE),
    .progress = TRUE,
    .id = "iter" # Automatically adds an iteration column
)

write_parquet(results, here(OUTPUT_PATH, RESULTS_FILE))

message(glue("Finished {N_SIMULATIONS} simulations."))

t2 <- Sys.time()

message("Simulation process finished.")
t2-t1
```


```{r}
# Read and stack all draw files into a single data frame
results <- read_parquet(here(OUTPUT_PATH, RESULTS_FILE))

p_values <- results |> filter(term == "tx1") |> 
    pull(`Pr...z..`)

hist(p_values, breaks = 20)

mean(p_values < 0.05)
```

### Sim with Interaction

```{r}
N_SIMULATIONS <- 1000
OUTPUT_PATH <- here("2-hosp", "output", "sim-resampling-H0-no-int-freq")
RESULTS_FILE <- "sim-resampling-H0-linear-int-freq.parquet"
N_CORES <- 8

t1 <- Sys.time()

message(glue("Starting {N_SIMULATIONS} new simulations on {N_CORES} cores..."))

future::plan(future.callr::callr, workers = N_CORES)

# --- Run Simulations in Parallel ---
results_int <- furrr::future_map_dfr(
    .x = 1:N_SIMULATIONS,
    .f = ~ run_simulation_iteration_int(
        iter_num = .x,
        full_data = df
    ),
    .options = furrr_options(seed = TRUE),
    .progress = TRUE,
    .id = "iter" # Automatically adds an iteration column
)

write_parquet(results_int, here(OUTPUT_PATH, RESULTS_FILE))

message(glue("Finished {N_SIMULATIONS} simulations."))

t2 <- Sys.time()

message("Simulation process finished.")
t2-t1
```

```{r}
# Read and stack all draw files into a single data frame
results_int <- read_parquet(here(OUTPUT_PATH, RESULTS_FILE))

p_values <- results_int |> filter(term == "tx1") |> 
    pull(`Pr...z..`)

hist(p_values, breaks = 20)

mean(p_values < 0.05)
```

### Sim Second Order

```{r}
N_SIMULATIONS <- 1000
OUTPUT_PATH <- here("2-hosp", "output", "sim-resampling-H0-no-int-freq")
RESULTS_FILE <- "sim-resampling-H0-second-order.parquet"
N_CORES <- 8

t1 <- Sys.time()
future::plan(future.callr::callr, workers = N_CORES)

# --- Run Simulations in Parallel ---
results_second <- furrr::future_map_dfr(
    .x = 1:N_SIMULATIONS,
    .f = ~ run_simulation_iteration_second(
        iter_num = .x,
        full_data = df_ypprev
    ),
    .options = furrr_options(seed = TRUE),
    .progress = TRUE,
    .id = "iter"
)

write_parquet(results_second, here(OUTPUT_PATH, RESULTS_FILE))

message(glue("Finished {N_SIMULATIONS} simulations."))

t2 <- Sys.time()
t2-t1
```

```{r}
# Read and stack all draw files into a single data frame
results_second <- read_parquet(here(OUTPUT_PATH, RESULTS_FILE))

p_values <- results_second |> filter(term == "tx1") |> 
    pull(`Pr...z..`)

hist(p_values, breaks = 20)

mean(p_values < 0.05)
```