---
Title: Examining Type I Error based on Sim Data
---

## Setup
```{r}
# Load Libraries
library(arrow)
library(tidyverse)
library(furrr)
library(glue)
library(fs)
library(here)
library(rms)
library(VGAM)
```

## Load data

- underlying truths: 
- first order markov
- time follows third order polynomial
- treatment effect on y = 0
- yprev interacts fully with time

```{r}
set.seed(1234)

# Load full dataset
# If we reasign the treatment again and again, emergency room visits are a bit too rare and mess up transitions
# We therefore collapse staet 3 and 4
Hmisc::getHdata(simlongord)

df_full <- simlongord |> filter(tx == "0") |> 
    filter(id < 100000)

rm(simlongord)
```

## Simulation function

```{r}
run_simulation_iteration <- function(iter_num, base_path, full_data) {
    # This function runs one full simulation iteration.
    
    # --- 1. Setup for the current iteration ---
    set.seed(1234 + iter_num)


    tx_ids <- full_data |> 
        distinct(id) |> 
        pull(id) |> sample(180, replace = FALSE)

    soc_ids <- full_data |> 
        distinct(id) |> 
        pull(id) |> 
        setdiff(tx_ids) |> 
        sample(90, replace = FALSE)

    data_for_model <- full_data |> 
        filter(id %in% c(tx_ids, soc_ids)) |>
        mutate(
            tx = if_else(id %in% tx_ids, "1", "0"),
            tx = factor(tx, levels = c(0, 1)))
    
    rm(full_data)
    
    if (nrow(data_for_model) > 0) {
        model <- tryCatch({ 
            vglm(ordered(y) ~ yprev + lsp(time, 2) + tx,
              cumulative(reverse=TRUE, parallel=FALSE ~ lsp(time, 2)),
              data=data_for_model)
            
        }, error = function(e) {
            message(glue("ERROR in iteration {iter_num}: {e$message}"))
            
            saveRDS(data_for_model, file.path(iter_path, "problematic_data.rds"))
            
            return(NULL)
        })
        
        # --- 7. Save the results ONLY if the model ran successfully ---
        if (!is.null(model)) {
            summary_df <- summary(model)@coef3 |> data.frame() |> 
                rownames_to_column("term")

            return(summary_df)
        }
    }
    return(NULL)
}
```

## Run Parallelized Simulation
```{r}
N_SIMULATIONS <- 1500
OUTPUT_PATH <- here("2-hosp", "output", "sim-simdata-H0-freq")
RESULTS_FILE <- "sim-simdata-H0-VIOLET.parquet"
N_CORES <- 6

t1 <- Sys.time()

message(glue("Starting {N_SIMULATIONS} new simulations on {N_CORES} cores..."))

future::plan(future.callr::callr, workers = N_CORES)

# --- Run Simulations in Parallel ---
results <- furrr::future_map_dfr(
    .x = 1:N_SIMULATIONS,
    .f = ~ run_simulation_iteration(
        iter_num = .x,
        full_data = df_full
    ),
    .options = furrr_options(seed = TRUE),
    .progress = TRUE,
    .id = "iter" # Automatically adds an iteration column
)

write_parquet(results, here(OUTPUT_PATH, RESULTS_FILE))

message(glue("Finished {N_SIMULATIONS} simulations."))

t2 <- Sys.time()

message("Simulation process finished.")
t2-t1
```


```{r}
# Read and stack all draw files into a single data frame
results <- read_parquet(here(OUTPUT_PATH, RESULTS_FILE))

p_values <- results |> filter(term == "tx1") |> 
    pull(`Pr...z..`)

hist(p_values, breaks = 20)

mean(p_values < 0.05)
```