---
Title: Examining Type I Error based on Sim Data
---

## Setup
```{r}
# Load Libraries
library(ggplot2)
library(arrow)
library(tidyverse)
library(furrr)
library(glue)
library(fs)
library(here)
library(rms)
library(VGAM)
```

```{r}
source("./functions/jackknife_mcse.R")
```

## Load data

- underlying truths: 
- first order markov
- time follows third order polynomial
- treatment effect on y = 0
- yprev interacts fully with time

```{r}
set.seed(1234)

# Load full dataset
# If we reasign the treatment again and again, emergency room visits are a bit too rare and mess up transitions
# We therefore collapse staet 3 and 4
df_full <- read_parquet(here("2-hosp", "sim-data", "sim_data_po_const.parquet")) |> 
    # mutate(
    #     y = as.numeric(as.character(y)),
    #     y = if_else(y == 4, 3, y),
    #     y = if_else(y == 5, 4, y),
    #     yprev = if_else(yprev == "4", "3", yprev),
    #     yprev = factor(yprev)) |> 
    filter(tx == "0") |> 
    select(id, tx, y, yprev, time)


# model used for df_full_no_int

# vm <- vglm(
#   ordered(y) ~ tx + week + I(week^2) + I(week^3) + yprev + ecog_fstcnt + diagnosis,
#   cumulative(reverse = TRUE, parallel = FALSE ~ week + I(week^2) + week + I(week^3)),
#   data = df
#   )

# states 3 and 4 were already collapsed during model fitting
df_full_no_int <- read_parquet(here("2-hosp", "sim-data", "sim_data_vglm.parquet")) |> 
    select(id, tx, y, yprev, time)
```

## Simulation function

```{r}
run_simulation_iteration <- function(iter_num, base_path, full_data, model_formula, cumulative_arg, seed = 123, sample_size = 270) {
    # This function runs one full simulation iteration.
    
    # --- 1. Setup for the current iteration ---
    set.seed(seed + iter_num)


    tx_ids <- full_data |> 
        distinct(id) |> 
        pull(id) |> sample(round(0.5* sample_size), replace = FALSE)

    soc_ids <- full_data |> 
        distinct(id) |> 
        pull(id) |> 
        setdiff(tx_ids) |> 
        sample(round(0.5* sample_size), replace = FALSE)

    data_for_model <- full_data |> 
        filter(id %in% c(tx_ids, soc_ids)) |>
        mutate(
            tx = if_else(id %in% tx_ids, "1", "0"),
            tx = factor(tx, levels = c(0, 1)))
    
    rm(full_data)
    
    if (nrow(data_for_model) > 0) {
        model <- tryCatch({ 
            vglm(
                model_formula,
                cumulative_arg,
                data = data_for_model)
            
        }, error = function(e) {
            message(glue("ERROR in iteration {iter_num}: {e$message}"))
            
            return(NULL)
        })
        
        # --- 7. Save the results ONLY if the model ran successfully ---
        if (!is.null(model)) {
            summary_df <- summary(model)@coef3 |> data.frame() |> 
                rownames_to_column("term")

            return(summary_df)
        }
    }
    return(NULL)
}
```

## Type I Error for data w/o interaction

### Large N
```{r}
N_SIMULATIONS <- 1000
OUTPUT_PATH <- here("2-hosp", "output", "sim-simdata-H0-freq")
RESULTS_FILE_LARGE <- "sim-simdata-H0-no-int-1k.parquet"
N_CORES <- 8

# define model specs
main_formula <- ordered(y) ~ tx + poly(time, 3) + yprev
cumulative_formula <- cumulative(reverse = TRUE, parallel = FALSE ~ poly(time, 3))

future::plan(future.callr::callr, workers = N_CORES)

# --- Run Simulations in Parallel ---
results <- furrr::future_map_dfr(
    .x = 1:N_SIMULATIONS,
    .f = ~ run_simulation_iteration(
        iter_num = .x,
        full_data = df_full_no_int,
        model_formula = main_formula,
        cumulative_arg = cumulative_formula,
        sample_size = 1000,
        seed = 888
    ),
    .options = furrr_options(seed = TRUE),
    .progress = TRUE,
    .id = "iter" # Automatically adds an iteration column
)

write_parquet(results, here(OUTPUT_PATH, RESULTS_FILE))
```

### Small N

```{r}
RESULTS_FILE_SMALL <- "sim-simdata-H0-no-int-250.parquet"

results <- furrr::future_map_dfr(
    .x = 1:N_SIMULATIONS,
    .f = ~ run_simulation_iteration(
        iter_num = .x,
        full_data = df_full_no_int,
        model_formula = main_formula,
        cumulative_arg = cumulative_formula,
        sample_size = 250,
        seed = 888
    ),
    .options = furrr_options(seed = TRUE),
    .progress = TRUE,
    .id = "iter" # Automatically adds an iteration column
)

write_parquet(results, here(OUTPUT_PATH, RESULTS_FILE_SMALL))
```


```{r}
# Read and stack all draw files into a single data frame
results_l_n <- read_parquet(here(OUTPUT_PATH, RESULTS_FILE_LARGE))
results_s_n <- read_parquet(here(OUTPUT_PATH, RESULTS_FILE_SMALL))

p_values_l <- results_l_n |> filter(term == "tx1") |> 
    pull(`Pr...z..`)

p_values_s <- results_s_n |> filter(term == "tx1") |> 
    pull(`Pr...z..`)

hist(p_values_l, breaks = 200, main = "Large N (1000)")
hist(p_values_s, breaks = 200, main = "Small N (250)")

mean(p_values_l < 0.05)
jackknife_mcse(p_values_l < 0.05)
mean(p_values_s < 0.05)
jackknife_mcse(p_values_s < 0.05)
```

## Bayesian Simulation

```{r}
run_simulation_iteration <- function(iter_num, base_path, full_data, model_formula, prior_spec = NULL) {
    # This function runs one full simulation iteration.
    
    # --- 1. Setup for the current iteration ---
    set.seed(123 + iter_num)
    iter_path <- file.path(base_path, glue("run_{iter_num}"))
    if (!dir.exists(iter_path)) {
        dir.create(iter_path, recursive = TRUE)
    }

    # Resample from data with no effect
    tx_ids <- full_data |> 
        distinct(id) |> 
        sample_frac(2/3) |> pull(id)

    data_for_model <- full_data |> 
        mutate(
            tx = if_else(id %in% tx_ids, "1", "0"),
            tx = factor(tx, levels = c(0, 1)))
    
    rm(full_data)


    # --- 5. Save the data used for model fitting ---
    saveRDS(data_for_model, file.path(iter_path, "data_for_model.rds"))


    # --- 6. Fit the Model and Save ---

    # we'll stick to evaluating type I error rate via OR of tx for the time being, then we don't need to marginalize
   
    if (nrow(data_for_model) > 0) {
        options(mc.cores = 1)
        dd <- datadist(data_for_model)
        options(datadist = 'dd')

        # Forcefully place the 'dd' object into the global environment of the worker.
        assign("dd", dd, envir = .GlobalEnv)
        on.exit(rm(dd, envir = .GlobalEnv))

        blrm_args <- list(
            formula = model_formula,
            data = data_for_model,
            ppo = ~ time,
            cppo = function(y) y,
            refresh = 0,
            iter = 2000,
            chains = 4,
            seed = 1234,
            loo = FALSE,
            method = "sampling"
        )
        
        if (!is.null(prior_spec)) {
            blrm_args$pcontrast <- prior_spec
        }

        model <- tryCatch({
            do.call(blrm, blrm_args)
        }, error = function(e) {
            message(glue("ERROR in iteration {iter_num}: {e$message}"))
            
            saveRDS(data_for_model, file.path(iter_path, "problematic_data.rds"))
            
            return(NULL)
        })
        
        # --- 7. Save the results ONLY if the model ran successfully ---
        if (!is.null(model)) {
            # Save the full model object
            saveRDS(model, file.path(iter_path, "model_object.rds"))
            
            # Save just the MCMC draws to a separate file
            saveRDS(as.data.table(model$draws), file.path(iter_path, "model_draws.rds"))

            rhat_values <- stanDx(model) |> 
                data.frame() |> 
                rownames_to_column()  |> 
                select(-n_eff) |> 
                pivot_wider(names_from = rowname, values_from = Rhat)

            saveRDS(rhat_values, file.path(iter_path, "rhat_values.rds"))

            ess_ratios <- stanDx(model) |> 
                data.frame() |> 
                rownames_to_column()  |> 
                select(-Rhat) |> 
                pivot_wider(names_from = rowname, values_from = n_eff) |> 
                mutate_all(~ . / (model$iter * model$chains))

             saveRDS(ess_ratios, file.path(iter_path, "ess_ratios.rds"))
        }
    }
    # Return a status message for progress tracking
    return(glue("Iteration {iter_num} completed."))
}
```

