---
Title: Examining serial correlation
---

```{r}
library(tidyverse)
library(Hmisc)
library(arrow)
```

```{r}
df <- read_parquet("./1-qol/sim-data/sim_data_po_forward.parquet")
```

```{r}
corr <-
  df |>
    filter(tx == 0) |> 
    select(id, time, y) |>
    arrange(time) |>
    mutate(y = as.integer(y)) |>
    pivot_wider(names_from = time, values_from = y) |>
    ungroup() |>
    select(-id) |>
    cor(method="spearman", use="pairwise.complete.obs")

corr |>
  as.data.frame() |>
  rownames_to_column() |>
  pivot_longer(-rowname) |>
  mutate(rowname = as.integer(rowname), name = as.integer(name)) |>
  filter(rowname < name) |> #remove tiles below diagonal, because redundant
  mutate(rowname = as.factor(rowname), name = as.factor(name)) |>
  ggplot() + 
    aes(x=rowname, y=name, fill=value) +
    geom_tile() +
    geom_text(mapping=aes(x=rowname, y=name, label=round(value, 2)),
              color="black",
              size = 3) +
    scale_fill_viridis_c(limits=c(-0.01,1), n.breaks = 10) +
    expand_limits(value = c(0, 1)) +
    # cowplot::theme_half_open(font_size=FONT_SIZE,
    #           font_family = "Source Sans Pro") +
    theme(plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    theme(axis.line = element_blank(),
          axis.ticks = element_blank()) +
    theme(legend.key.height = unit(0.8, "in")) +
    labs(x="Study week",
         y="Study week",
         fill="", 
         subtitle = "Simulated Data")

plotCorrM(corr)[[2]]
```

The estimated serial correlation is very weak, and doesn't decay with time. That's likely why model with random intercept fits the data (almost) as well as the markov model.